### ISSUE TITLE
Use Google Cloud Storage for my files

### ISSUE THREAD

**Issue by EZFRICA** [CitizenLabDotCo/citizenlab-docker#10]
How do I go about the configuration

**Comment by kogre** [comment]
This is currently not supported in our setup. You could explore to mounting the `uploads/` folder as a google cloud volume using the [Docker GCS Storage driver](https://docs.docker.com/registry/storage-drivers/gcs/).

But unfortunately this is something we can't support for you, or help you with directly. The current setup is intended to run on a single server and use local storage.
