### ISSUE TITLE
docker back-essential-latest fails after startup

### ISSUE THREAD

**Issue by slfhstr** [CitizenLabDotCo/citizenlab-docker#12]
CitizenLab docker installed on fresh VPS : no other software installed
But `docker-compose up -d` fails consistently after 20-30 seconds
```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                     PORTS                                                                                NAMES
0e6a8d58c621   caddy:2                                  "caddy run --config …"   24 seconds ago   Up 22 seconds              0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 2019/tcp   citizenlab-docker_caddy_1
22e0b1dff673   citizenlabdotco/back-essential:latest    "bundle exec que"        24 seconds ago   Exited (1) 3 seconds ago                                                                                        cl-docker-que
e2e0b2e7a39c   citizenlabdotco/back-essential:latest    "/bin/sh -c 'puma -C…"   24 seconds ago   Exited (1) 3 seconds ago                                                                                        cl-docker-back-web
a667c308c247   memcached:alpine                         "docker-entrypoint.s…"   26 seconds ago   Up 24 seconds              11211/tcp                                                                            citizenlab-docker_memcached_1
aeed381cc29c   postgis/postgis:12-3.1                   "docker-entrypoint.s…"   26 seconds ago   Up 24 seconds              5432/tcp                                                                             citizenlab-docker_postgres_1
2035c359fb6b   rabbitmq:3.7                             "docker-entrypoint.s…"   26 seconds ago   Up 24 seconds              4369/tcp, 5671-5672/tcp, 25672/tcp                                                   cl-docker-back-rabbit
f2ecad300bf4   citizenlabdotco/front-essential:latest   "docker-entrypoint.s…"   26 seconds ago   Up 24 seconds                                                                                                   cl-docker-front
```

How can I resolve this ?
CitizenLabs looks v.interesting

**Comment by slfhstr** [comment]
`cl-docker-back-rabbit | 2021-09-04 15:07:11.346 [warning] <0.521.0> closing AMQP connection <0.521.0> (172.18.0.6:42754 -> 172.18.0.3:5672, vhost: '/', user: 'guest'):` leads to failure of back-essential ?

**Comment by slfhstr** [comment]
So without any guidance available, I scrapped the VPS and reinstalled it with fresh Ubuntu 20.04.
Followed instructions **to the letter**
Good news : containers do stay up and do not exit shortly after launch.
Bad news : site does not respond, blank screen except Error 502
Tried in different browsers.
Any advice please ?
CitizenLab looks perfect for a democracy project.
Providing of course the page can actually load.

**Comment by slfhstr** [comment]
So after a reinstall and pulling docker images down, the site is now loading !

Yay ! 🍾 

So I am closing this.
I look forward to exploring the platform.

**Comment by stephan-schmidt** [comment]
@timconsidine thanks for bringing that up.

What did you do other than in the deployment guide explained https://developers.citizenlab.co/start-deployment?
I am still getting a blank screen except `Error 502` and when invoking the db this error appears `Could not establish TCP connection to rabbitmq:5672: Connection refused - connect(2) for 172.18.0.4:5672` 

Do you have any insights?

**Comment by slfhstr** [comment]
Eventually got it working on the 3rd fresh install

Best wishes

Tim Considine

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stephan-schmidt** [comment]
Thanks so much. Tried it now on a Google VM instance and Digital Ocean - containers are up and running, but blank page and spinning loader in the browser tab on Chrome only. Also tried it with leaving out the domain and just using the IP address as mentioned in the docs editing the caddy file. Still the same result. 
![image](https://user-images.githubusercontent.com/1506096/148852372-d1d115b1-f8d7-4b7f-9d30-8c1d08b9b915.png)
Does @kogre  has an idea?

**Comment by stephan-schmidt** [comment]
Got it working! Had to wait way longer after startup than anticipated. thanks though for the encouragement!
