### ISSUE TITLE
Production deployment: ActiveRecord::RecordInvalid: Validation failed

### ISSUE THREAD

**Issue by matlendzi1** [CitizenLabDotCo/citizenlab-docker#14]
Hi there,
i have a problem with step 7 of your deployment tutorial. When I run db:setup i get the following error after "Execute db:abort_if_pending_migrations":

rake aborted! ActiveRecord::RecordInvalid: Validation failed: Settings {:fragment=>"#/password_login", :error=>"RequiredSettings", :human_message=>"The active feature '#/password_login' did not have all the required settings [\"minimum_length\", \"phone\"] in schema b17092c7-5ced-5074-8ba4-38b17cb66ccc"}

Could you help me?
Thank you!

This is the full message:

`$ docker-compose run --rm web rake db:setup DISABLE_DATABASE_ENVIRONMENT_CHECK=1 --trace
Creating citizenlab-docker_web_run ... done
** Invoke db:setup (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:create
Database 'clab' already exists
** Invoke db:extensions (first_time)
** Invoke environment 
** Execute db:extensions
** Invoke environment 
** Invoke db:schema:load (first_time)
** Invoke db:load_config 
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:schema:load
** Invoke db:seed (first_time)
** Invoke db:load_config 
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Settings {:fragment=>"#/password_login", :error=>"RequiredSettings", :human_message=>"The active feature '#/password_login' did not have all the required settings [\"minimum_length\", \"phone\"] in schema b17092c7-5ced-5074-8ba4-38b17cb66ccc"}
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/validations.rb:53:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:302:in `block in save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:302:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:55:in `create!'
/cl2_back/db/seeds/citizenlab.rb:11:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/cl2_back/db/seeds.rb:4:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:566:in `block in load_seed'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:640:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:566:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/tasks/database_tasks.rb:450:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/railties/databases.rake:392:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/sentry-ruby-core-4.7.2/lib/sentry/rake.rb:20:in `execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => db:setup => db:seed`

**Comment by alexander-cit** [comment]
Thanks a lot for reporting! We've just merged the fix into the master. Could you please retry the 6th and 7th steps?

**Comment by matlendzi1** [comment]
Hi Alexander, thank you for your promt response. I started the whole thing from scratch (reinstall docker etc.) and repeated all tutorial steps but unfortunaly the result is the same. Does git clone https://github.com/CitizenLabDotCo/citizenlab-docker.git get the actual master branch?

This is the error message again:

`sudo docker-compose run --rm web rake db:setup DISABLE_DATABASE_ENVIRONMENT_CHECK=1
Creating network "cl-docker" with the default driver
Creating volume "citizenlab-docker_caddy_data" with default driver
Creating volume "citizenlab-docker_caddy_config" with default driver
Creating citizenlab-docker_memcached_1 ... done
Creating citizenlab-docker_postgres_1  ... done
Creating cl-docker-back-rabbit         ... done
Creating citizenlab-docker_web_run     ... done
Database 'clab' already exists
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Settings {:fragment=>"#/password_login", :error=>"RequiredSettings", :human_message=>"The active feature '#/password_login' did not have all the required settings [\"minimum_length\", \"phone\"] in schema b17092c7-5ced-5074-8ba4-38b17cb66ccc"}
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/validations.rb:53:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:302:in `block in save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:302:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/suppressor.rb:48:in `save!'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:55:in `create!'
/cl2_back/db/seeds/citizenlab.rb:11:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/cl2_back/db/seeds.rb:4:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:566:in `block in load_seed'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:640:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/engine.rb:566:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/tasks/database_tasks.rb:450:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/railties/databases.rake:392:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sentry-ruby-core-4.7.2/lib/sentry/rake.rb:20:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)`

**Comment by alexander-cit** [comment]
Indeed, the image wasn't updated on DockerHub. Now it should be fixed. Could you please try again the 6th and 7th steps?

**Comment by matlendzi1** [comment]
It works!! Thank you very much!
