### ISSUE TITLE
Internal Server error after reboot

### ISSUE THREAD

**Issue by mwaliczek** [CitizenLabDotCo/citizenlab-docker#15]
Hello,

I'm trying to setup environment and deploy application like it was described here: https://developers.citizenlab.co/start-deployment on Ubuntu Server 22.04. All steps are going just fine, I get application up and running, can perform customization, etc. and all changes are being saved. Then after a machine reboot, every time when I try to save any change done using Admin Panel I receive a 500 Internal Server Error. App is available, I can navigate to the page and preview every content but not save anything.

All the docker componenets are up and running. If I repeat two steps form documentation, first executing `docker-compose stop `and then:
```
$ docker-compose run --rm web rake db:setup
$ docker-compose up -d
```

With .env option `DISABLE_DATABASE_ENVIRONMENT_CHECK=1` a DB is being recreated, all content is being lost but again I can perform any required change in Admin Panel up to the next reboot.

The only action performed after machine reboot to start the app is `docker-compose up -d`. Is there anything missing in what I do, is it a bug or is it by design?

**Comment by nTraum** [comment]
Hi @mwaliczek,

this is not by design. The application should continue working without errors even after restarts.

In order to help you, could you post the following log files:

1. Deploy the application as described in the deployment guide
2. Perform the customizations as you described
3. Reboot the machine as you described
4. Run `docker-compose logs web --follow` to see the live application logs in the terminal
5. Attempt your Admin changes again that trigger the 500 Internal Server Error
6. Post the logs here.

**Comment by mwaliczek** [comment]
Hello thank you for your response. I've given it some time as actually there were moments that it was working fine but then again it stopped today with the same error. 

It seems that nothing is showing up in the logs, I can see only the initial logs and when I perform required actions I cannot see them changing:

`ubuntusrv@ubuntusrv:~/citizenlab-docker$ docker-compose logs --follow web
Attaching to cl-docker-back-web
cl-docker-back-web | [7] Puma starting in cluster mode...
cl-docker-back-web | [7] * Puma version: 5.6.4 (ruby 2.7.5-p203) ("Birdie's Version")
cl-docker-back-web | [7] *  Min threads: 5
cl-docker-back-web | [7] *  Max threads: 5
cl-docker-back-web | [7] *  Environment: production
cl-docker-back-web | [7] *   Master PID: 7
cl-docker-back-web | [7] *      Workers: 2
cl-docker-back-web | [7] *     Restarts: (✔) hot (✖) phased
cl-docker-back-web | [7] * Preloading application
cl-docker-back-web | [7] * Listening on http://0.0.0.0:4000
cl-docker-back-web | [7] ! WARNING: Detected 3 Thread(s) started in app boot:
cl-docker-back-web | [7] ! #<Thread:0x0000564d0daa64e0 /usr/local/bundle/gems/semantic_logger-4.10.0/lib/semantic_logger/appender/async.rb:77 sleep_forever> - /usr/local/bundle/gems/semantic_logger-4.10.0/lib/semantic_logger/appender/async.rb:150:in 'pop'
cl-docker-back-web | [7] ! #<Thread:0x0000564d0d972650 /usr/local/bundle/gems/bunny-2.19.0/lib/bunny/heartbeat_sender.rb:46 sleep> - /usr/local/bundle/gems/bunny-2.19.0/lib/bunny/heartbeat_sender.rb:51:in 'sleep'
cl-docker-back-web | [7] ! #<Thread:0x0000564d0d972010 /usr/local/bundle/gems/bunny-2.19.0/lib/bunny/reader_loop.rb:35 sleep> - /usr/local/bundle/gems/bunny-2.19.0/lib/bunny/cruby/socket.rb:65:in 'select'
cl-docker-back-web | [7] Use Ctrl-C to stop
cl-docker-back-web | [7] - Worker 1 (PID: 39) booted in 0.01s, phase: 0
cl-docker-back-web | [7] - Worker 0 (PID: 38) booted in 0.02s, phase: 0`

I keep all of the files in a user home directory in a dedicated folder. Postgres files are also in the same place:

`ubuntusrv@ubuntusrv:~/citizenlab-docker$ ls
Caddyfile  docker-compose.yml  install.sh  LICENSE.md  postgresql-data  README.md  uploads
`

It seems that this is related to something that is being set in the database (I've selected 2 languages: Polish and English). What I've checked:

1. Create DB dump by executing: `docker exec -t citizenlab-docker_postgres_1 pg_dumpall -c -U postgres > dump_'date +%d-%m-%Y"_"%H_%M_%S'.sql`
2. Recreating DB by: `docker-compose run --rm web rake db:setup`
3. Everything works after pt.2 and every reboot (I did 4-5 of them both machine reboot and docker-container reboot) up until pt.4
4. Restore DB from the dump by runnig only a postgres container and then `cat dump_23-06-2022_17_14_08.sql | docker exec -i citizenlab-docker_postgres_run_fe9be2fd185e psql -U postgres`
5. Restart docker-containers.
6. It stops working again by throwing 500: Internal Server Error

**Comment by mwaliczek** [comment]
I manged to find the way on how to get the error (I think) but only on an app interface level, not an application one. Steps to reproduce:

1. Deploy the application as described in the deployment guide (having it with default settings).

2. Go to Admin Panel -> Settings -> General and change language settings to have Polish and English (in that order so: Polish, English) like in this file: ![Step1](https://user-images.githubusercontent.com/87702499/175587888-8c3cc9e0-9c67-4a1b-b6df-e94f2ef45f25.png)

3. Click Save (if a restart would take place at this moment, everything would be working fine when back again).

4. Go to Admin Panel -> Settings -> Customize and provide only a values for Polish language, levaing EN values with red light sign. Provide values for: 'Header text for non-registered visitors', 'Homepage customizable section' and all other fields for Polish language. So fill in all input boxes and text boxes but only in first language, leaving all English input boxes with red light.

5. Reboot or run `docker-compose stop` and `docker-compose up -d`

6. Have an 500 Internal Server Error like in this file: ![Step2](https://user-images.githubusercontent.com/87702499/175587939-4ad6fd5b-5bad-4bd9-abbf-8086859f9b26.png)

Now you can
not change anything on an application level. DB level works just fine, I've opend a 5432 port from docker container, gathered IP with docker inspect [ID] and connect to DB from remote. I was able to change anything on DB layer so it's not tight to files or DB permission level.

As one can Save changes without any prompt, application should work without providing data in Admin Panel -> Settings -> Customize to all (EN in this case) language. Othervise there should be a prompt (popup or something) if EN values are required, preventing one from saving changes.

**Comment by mwaliczek** [comment]
After further investigation: 

A problem occurrs when homepage_info_multiloc in app configurations table is set to any value. So if one provides a value in Homepage customizable section like here:

![Step3](https://user-images.githubusercontent.com/87702499/175768579-7d5341e3-7ee9-4c0e-ba83-d60210c51b8a.png)

After a reboot editing stops. Steps to reproduce:

1. Deploy the application as described in the deployment guide (having it with default settings).

2. Run the application as described in the deployment guide.

3. Go to Admin Panel -> Settings -> General and make sure that default laguage was set (EN for this case).

4. Go to Admin Panel -> Settings -> Customize and apply a value for 'Homepage customizable section'

5. Reboot.

6. Go to Admin Panel -> Settings -> General

8. Now editing leads to a 500 Internal Server Error

9. Connect to DB and execute: `UPDATE app_configurations SET homepage_info_multiloc = null`

10. Navigate to Admin Panel -> Settings editing starts working again without any reboot.

11. Navigate to Admin Panel -> Settings -> General and try setting a value for 'Homepage customizable section' form.

12. Saving leads to a 500 Internal Server Error

13. Refresh the page, navigate to Home page and then navigate back to Admin Panel -> Settings -> Customize and try to change anything except 'Homepage customizable section'.

14. Admin Panel -> Settings editing works.

16. Adding Projects, Activities, Comments, etc. and editing them does not work.

18. Reboot.

19. Adding Projects, Activities, Comments, etc. starts working again.

**Comment by alexander-cit** [comment]
Thanks for the report!

It's really weird that a reboot makes any difference. But restarting docker containers indeed can matter.

> It seems that nothing is showing up in the logs

The logs are not enabled by default. Could you please add this line to the `.env` file to enable them? 
```
RAILS_LOG_TO_STDOUT=true
```
And then please restart docker-compose, reproduce the "500: Internal Server Error" error and post the logs here.

P.S. It should be a clue to solve https://github.com/CitizenLabDotCo/citizenlab/issues/2371 too.

**Comment by mwaliczek** [comment]
the same as in [here](https://github.com/CitizenLabDotCo/citizenlab/issues/2371)

**Comment by alexander-cit** [comment]
Thanks for reaching out!
The issue was resolved here https://github.com/CitizenLabDotCo/citizenlab/issues/2369#issuecomment-1212033780
