### ISSUE TITLE
Cannot delete a Project

### ISSUE THREAD

**Issue by mwaliczek** [CitizenLabDotCo/citizenlab-docker#16]
When trying to delete a project and error occurs. Steps to reproduce:

1. Deploy the application as described in the deployment guide (having it with default settings).

2. Run the application as described in the deployment guide.

4. Navigate to Admin -> Settings -> Project and add a new project with Published status.

5. Deleting a project leads to an error like here:

![Step4](https://user-images.githubusercontent.com/87702499/175770580-dfbe6e48-c717-409d-8a04-043986dc33b9.png)

An error is related to a Foreign Key settings in DB. Steps to reproduce:

1. Login to DB.

2. Find an ID of a project to delete.

3. Execute Delete for example: `DELETE FROM "public"."projects" WHERE  "id"='fa133ac8-71c1-4360-ae37-3730eae4c220';`

4. Have foreign key constraint violation as below:

![Step5](https://user-images.githubusercontent.com/87702499/175770644-21d413b3-940f-4189-bcc2-54e6ce2f2141.png)

5. Executing `ALTER TABLE projects_allowed_input_topics DROP CONSTRAINT fk_rails_91bda1f137` solves the deletion error on DB level but event without a foreign key constraint deleting from Web Interface does not work.

**Comment by alexander-cit** [comment]
Being discussed here https://github.com/CitizenLabDotCo/citizenlab/issues/2369

**Comment by alexander-cit** [comment]
Resolved with https://github.com/CitizenLabDotCo/citizenlab/issues/2369
Thanks for reaching out!
