### ISSUE TITLE
Database seeding fails

### ISSUE THREAD

**Issue by marinpurgar** [CitizenLabDotCo/citizenlab-docker#7]
`docker-compose run --rm web rake db:create db:migrate db:seed` fails with:

```rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "app_configurations" does not exist
LINE 1: SELECT "app_configurations".* FROM "app_configurations" ORDE...
                                            ^
```
Tested on AWS EC2 Instance with AL2 and Ubuntu 20.04 local install.

**Comment by kogre** [comment]
Hey @marinpurgar , thanks for reporting.

Confirming this is a blocking issue at the moment. We're working on resolving it as soon as possible and will update you when it's released.

**Comment by marinpurgar** [comment]
After investigation I found that it's the issue with the https://github.com/CitizenLabDotCo/citizenlab/blob/master/back/config/initializers/reload_cl_settings.rb
The database is accessed in the initializer.
One of the possible solution would be to check if the table accessed is available like:
```
if ActiveRecord::Base.connection.tables.include?('app_configurations')
  # initializer code goes here
end
```
Or simply move the code out of the intializer to the proper place.

**Comment by kogre** [comment]
Thanks @marinpurgar , the issue has been resolved and a new Docker image has been published with the fix.
