### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by EZFRICA** [CitizenLabDotCo/citizenlab-docker#8]
Hello
After following the steps to deploy your documentation, I receive this error : ERR_SSL_PROTOCOL_ERROR

[developers.citizenlab.co](https://developers.citizenlab.co/start-deployment/)

**Comment by kogre** [comment]
Hello @EZFRICA 

This error happens when for some reason, the webserver (Caddy) isn't able to provision a https certificate. Can you access it over `http://` instead of `https://`?

What are you using as the value `CL_SETTINGS_HOST=` in the .env file? Is it the IP address of the server or a domain name?

**Comment by EZFRICA** [comment]
I am using the IP address. When I try to access it with http:// it redirects me to https://

**Comment by kogre** [comment]
It seems that for some reason, Caddy is not accepting the http traffic. A https certificate with an IP address doesn't work without specific configuration in Caddy unfortunately. This is wrong in the documentation, we'll update it to make that clear, or alternatively find a solution to make it work with an IP address.

Thanks for helping us uncover that!

The easiest way to resolve it is to set up a domain name for your server, and configure that in the `.env` file. I suspect you'll want to do that in any case?

**Comment by EZFRICA** [comment]
Can you show me how to setup with the domain name?

**Comment by EZFRICA** [comment]
It would be really nice to have the option to use the service without https. Can you help me configure the server so that it is available in http.

**Comment by kogre** [comment]
That depends on your DNS hosting provider. If you have one already, you can probably register the domain name you want to use for your platform there. You'll then need to add a DNS record of the `A` type, with its value being the IP address of your server.

Then, you need to update the `.env` file and add the domain name as the `CL_SETTINGS_HOST` value.

We strongly advise to always use https to protect your data, and the data of your users. Additionally, browsers will give visible warnings that will scare off your users. Caddy takes care of the https by itself, as long as you have your domain name configured.

**Comment by EZFRICA** [comment]
I will try your solution and get back to you.

I found this https://github.com/caddyserver/caddy/issues/3219 for disabling http-to-https redirect from Caddyfile. Does the version of Caddyfile you are using support this.

**Comment by EZFRICA** [comment]
Here is the code I used to access the application in http with the IP address of my virtual machine. With this code you will also have access to the domain name in http and https.

`Address IP {

    handle /uploads/* {
            root /uploads/* /uploads/
            uri strip_prefix /uploads
            file_server
    }

    @back_requests {
            path_regexp ^/(api|auth|web_api|admin_api|hooks)/(.*)$
    }

    reverse_proxy @back_requests web:4000 {
            header_up Host {http.reverse_proxy.upstream.hostport}
    }

    reverse_proxy front:3000
}

http:// {

    handle /uploads/* {
            root /uploads/* /uploads/
            uri strip_prefix /uploads
            file_server
    }

    @back_requests {
            path_regexp ^/(api|auth|web_api|admin_api|hooks)/(.*)$
    }

    reverse_proxy @back_requests web:4000 {
            header_up Host {http.reverse_proxy.upstream.hostport}
    }

    reverse_proxy front:3000
}

:80 {

    handle /uploads/* {
            root /uploads/* /uploads/
            uri strip_prefix /uploads
            file_server
    }

    @back_requests {
            path_regexp ^/(api|auth|web_api|admin_api|hooks)/(.*)$
    }

    reverse_proxy @back_requests web:4000 {
            header_up Host {http.reverse_proxy.upstream.hostport}
    }

    reverse_proxy front:3000
}

{$CL_SETTINGS_HOST} {

    handle /uploads/* {
            root /uploads/* /uploads/
            uri strip_prefix /uploads
            file_server
    }

    @back_requests {
            path_regexp ^/(api|auth|web_api|admin_api|hooks)/(.*)$
    }

    reverse_proxy @back_requests web:4000 {
            header_up Host {http.reverse_proxy.upstream.hostport}
    }

    reverse_proxy front:3000
}`
